### ISSUE TITLE
Update node engine value

### ISSUE THREAD

**Issue by bradcerasani** [nomaed/karabiner-profile-switch#2]
`"node": "6"` is a bit dated and restrictive. Perhaps `">=6.0.0"`?

**Comment by nomaed** [comment]
Feel free to create a PR :)
I've been using it this way with Node 7 and never got any warning.

At any rate, I see that new versions of Karabiner re-added switching profiles, so this package is probably not needed anymore.

**Comment by bradcerasani** [comment]
Still using this package while https://github.com/tekezo/Karabiner-Elements/pull/170 awaits merge – need to use an outdated version to support a hyper key.
